language: rust
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
env:
  global:
    - CARGO_TERM_COLOR=always
    - RUST_BACKTRACE=1
    - RUST_LOG=info
cache: cargo
script:
  - cargo test
  - cargo test --benches
  - cargo test --release
  - cargo test --release --benches
